Header header
geometry_msgs/Vector3 position
geometry_msgs/Vector3 mag_ned #nT
geometry_msgs/Vector3 mag_ned_log #nT
float32 distance
float32 amp #nT
float32 amp_log #log(nT)
float32 bearing #rad 
float32 max_interval
float32 min_interval
float32 corr_north_east
int32 num_bad_interval

geometry_msgs/Vector3 max_ang_vel
geometry_msgs/Vector3 mean_ang_vel
geometry_msgs/Vector3 sum_ang_vel

bool flag_inlier
bool flag_high_snr
geometry_msgs/Vector3 median
geometry_msgs/Vector3 std




