Header header
int32 frame_index
int32 frame_num
int32 feature_num
geometry_msgs/Vector3 gt_position
geometry_msgs/Vector3 position
geometry_msgs/Vector3 rpy
float64 place_recognition_time
float64 img_query_time
float64 add_frame_time
float64[] connect_time
float64 connect_time_total
float64 recent_opt_time
int32 opt_count
float64 add_descriptor_time
float64 add_mag_time
float64 debug_img_time
bool flag_detect
bool flag_connect
geometry_msgs/Vector3 mag_enu_log
geometry_msgs/Vector3 geomag
float64 mag_bearing


