Header header
int32 solver_flag
geometry_msgs/Vector3 Ps
geometry_msgs/Vector3 Rs_x
geometry_msgs/Vector3 Rs_y
geometry_msgs/Vector3 Rs_z
geometry_msgs/Vector3 Rs_rpy
geometry_msgs/Vector3 g 

geometry_msgs/Vector3 ric_x
geometry_msgs/Vector3 ric_y
geometry_msgs/Vector3 ric_z
geometry_msgs/Vector3 ric_rpy

geometry_msgs/Vector3 Vs
geometry_msgs/Vector3 acc_enu
geometry_msgs/Vector3 Bas
geometry_msgs/Vector3 Bgs
float64 scale

